// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-dashboard/ForestGreen.tsx": () => import("../components/mockups/admin-dashboard/ForestGreen.tsx"),
  "./components/mockups/admin-dashboard/NavyAmber.tsx": () => import("../components/mockups/admin-dashboard/NavyAmber.tsx"),
  "./components/mockups/admin-dashboard/SlateTeal.tsx": () => import("../components/mockups/admin-dashboard/SlateTeal.tsx"),
  "./components/mockups/dashboard/Feed.tsx": () => import("../components/mockups/dashboard/Feed.tsx"),
  "./components/mockups/dashboard-redesign/RenderStyle.tsx": () => import("../components/mockups/dashboard-redesign/RenderStyle.tsx"),
  "./components/mockups/dashboard-redesign/TimelineFeed.tsx": () => import("../components/mockups/dashboard-redesign/TimelineFeed.tsx"),
  "./components/mockups/landing-directions/BoldBlue.tsx": () => import("../components/mockups/landing-directions/BoldBlue.tsx"),
  "./components/mockups/landing-directions/CleanBlue.tsx": () => import("../components/mockups/landing-directions/CleanBlue.tsx"),
  "./components/mockups/landing-directions/CleanOrange.tsx": () => import("../components/mockups/landing-directions/CleanOrange.tsx"),
  "./components/mockups/landing-directions/WarmBlue.tsx": () => import("../components/mockups/landing-directions/WarmBlue.tsx"),
  "./components/mockups/sentconnect-hero/InteractiveFeed.tsx": () => import("../components/mockups/sentconnect-hero/InteractiveFeed.tsx"),
  "./components/mockups/sentconnect-ui/AdminDashboard.tsx": () => import("../components/mockups/sentconnect-ui/AdminDashboard.tsx"),
  "./components/mockups/sentconnect-ui/PostFeed.tsx": () => import("../components/mockups/sentconnect-ui/PostFeed.tsx")
};
